---

name: Packer - build, tag, push

on:
  push:
    tags:
      - v*

jobs:
  packer_build_tag_and_publish:
    runs-on: ubuntu-latest
    name: packer build tag and publish

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Init
      - name: Init packer
        run: packer init .

      # validate templates
      - name: Validate Template
        run: packer validate docker-buffalo.pkr.hcl

      # build artifact
      - name: Build Artifact
        run: packer build -color=false -on-error=abort docker-buffalo.pkr.hcl
        env:
          PACKER_LOG: 1

      # docker login
      - name: Docker login
        run: docker login --username ${{ secrets.MY_DOCKER_LOGIN }} --password ${{ secrets.MY_DOCKER_PWD }}

      # docker push
      - name: docker push
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          docker push deogracia/${VERSION}

      # docker logout
      - name: Docker logout
        run: docker logout
