---

name: Packer - build, tag, push

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    tags:
      - v*

jobs:
  packer_build_tag_and_publish:
    runs-on: ubuntu-latest
    name: packer build tag and publish

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Init
      - name: Init packer
        run: packer init .

      # validate templates
      - name: Validate Template
        run: packer validate docker-buffalo.pkr.hcl

      # build artifact
      - name: Build and docker push artifact
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo "VERSION=${VERSION}"

          packer build -color=false \
                 -on-error=abort \
                 -var "docker_image_version=${VERSION}" \
                  docker-buffalo.pkr.hcl

          echo "${{ secrets.MY_DOCKER_PWD }}" | docker login \
            --username ${{ secrets.MY_DOCKER_LOGIN }} \
            --password-stdin

          docker push "deogracia/my-buffalo:${VERSION}"

          docker logout
        env:
          PACKER_LOG: 1
